import Song1 from "./assets/Song1.mp3";
import Song2 from "./assets/Song2.mp3";
import Song3 from "./assets/Song3.mp3";
import Song4 from "./assets/Song4.mp3";

const songs = [
  {
    name: "Dandelions",
    singer: "Ruth B.",
    src: Song1,
    image:
      "https://i.pinimg.com/564x/f9/2b/b6/f92bb6cfcac1c5481c8ce82b4f800d5a.jpg",
      lyrics:[
        { line: "", time: 41 },
        { line: "Arittake no yume o kakiatsume", note: "Intro", time: 47 },
        { line: "Sagashi-mono o sagashi ni yuku no sa", time: 53 },
        { line: "ONE PIECE", time: 59 },
        {
          line: "Rashinban nante jyutai no moto",
          note: "Verse 1",
          time: 65,
        },
        { line: "Netsu ni ukasare kaji o toru no sa", time: 71 },
        { line: "Hokori kabutteta takara no chizu mo", time: 77 },
        { line: "Tashikameta no nara densetsu jyanai!", time: 82 },
        { line: "Kojin teki na arashi wa dareka no", time: 89 },
        { line: "BIORHYTHM (baiorizumu) nokkatte", time: 94 },
        { line: "omoi sugose ba ii", time: 98 },
        { line: "arittakeno yume o kakiatsume", time: 103 },
        { line: "sagashi mono sagashini yuku no sa", time: 109 },
        { line: "POCKET (poketto) no COIN (koin), soreto", time: 112 },
        { line: "YOU WANNA BE MY FRIEND?", time: 115 },
        { line: "WE ARE, WE ARE ON THE CRUISE! WE ARE!", time: 124 },
        { line: "", time: 156 },
        { line: "zembu mani ukete shinji chattemo",note:"Verse 2", time: 162 },
        { line: "kata o osarete iippo LEAD (lidu) sa", time: 168 },
        { line: "kondo aetanara hanasu tsumorisa", time: 173 },
        { line: "sore kara no koto to kore kara no koto", time: 180 },
        { line: "tsumari itsumo PINCH (pinchi) wa dareka ni", time: 186 },
        { line: "APPEAL (apiiru) dekiru ii CHANCE (chansu)", time: 192 },
        { line: "ji ishiki kajyoo ni!", time: 194 },
        { line: "shimittareta yoru o buttobase!", time: 201 },
        { line: "takara bako ni KYOUMI wa nai kedo", time: 206 },
        { line: "POCKET (poketto) ni roman, soreto", time: 210 },
        { line: "YOU WANNA BE MY FRIEND?", time: 213 },
        { line: "WE ARE, WE ARE ON THE CRUISE! WE ARE!", time: 221 },
        { line: "arittakeno yume o kakiatsume", time: 226 },
        { line: "sagashi mono sagashini yuku no sa", time: 231 },
        { line: "POCKET (poketto) no COIN (koin), soreto", time: 235 },
        { line: "YOU WANNA BE MY FRIEND?", time: 240 },
        { line: "WE ARE, WE ARE ON THE CRUISE!", time: 243 },
        { line: "WE ARE!", time: 246 },
        { line: "WE ARE!", time: 249 },
        { line: "WE ARE!", time: 259 },
      ]
  },
  {
    name: "Send My Love",
    singer: "Adele ( cover by Sit Still, Look Pretty )",
    src: Song2,
    image:
      "https://i.pinimg.com/564x/2d/f3/87/2df38767b3db71d9edf93f4b82801be2.jpg",
      lyrics:[
        { line: "", time: 41 },
        { line: "Arittake no yume o kakiatsume", note: "Intro", time: 47 },
        { line: "Sagashi-mono o sagashi ni yuku no sa", time: 53 },
        { line: "ONE PIECE", time: 59 },
        {
          line: "Rashinban nante jyutai no moto",
          note: "Verse 1",
          time: 65,
        },
        { line: "Netsu ni ukasare kaji o toru no sa", time: 71 },
        { line: "Hokori kabutteta takara no chizu mo", time: 77 },
        { line: "Tashikameta no nara densetsu jyanai!", time: 82 },
        { line: "Kojin teki na arashi wa dareka no", time: 89 },
        { line: "BIORHYTHM (baiorizumu) nokkatte", time: 94 },
        { line: "omoi sugose ba ii", time: 98 },
        { line: "arittakeno yume o kakiatsume", time: 103 },
        { line: "sagashi mono sagashini yuku no sa", time: 109 },
        { line: "POCKET (poketto) no COIN (koin), soreto", time: 112 },
        { line: "YOU WANNA BE MY FRIEND?", time: 115 },
        { line: "WE ARE, WE ARE ON THE CRUISE! WE ARE!", time: 124 },
        { line: "", time: 156 },
        { line: "zembu mani ukete shinji chattemo",note:"Verse 2", time: 162 },
        { line: "kata o osarete iippo LEAD (lidu) sa", time: 168 },
        { line: "kondo aetanara hanasu tsumorisa", time: 173 },
        { line: "sore kara no koto to kore kara no koto", time: 180 },
        { line: "tsumari itsumo PINCH (pinchi) wa dareka ni", time: 186 },
        { line: "APPEAL (apiiru) dekiru ii CHANCE (chansu)", time: 192 },
        { line: "ji ishiki kajyoo ni!", time: 194 },
        { line: "shimittareta yoru o buttobase!", time: 201 },
        { line: "takara bako ni KYOUMI wa nai kedo", time: 206 },
        { line: "POCKET (poketto) ni roman, soreto", time: 210 },
        { line: "YOU WANNA BE MY FRIEND?", time: 213 },
        { line: "WE ARE, WE ARE ON THE CRUISE! WE ARE!", time: 221 },
        { line: "arittakeno yume o kakiatsume", time: 226 },
        { line: "sagashi mono sagashini yuku no sa", time: 231 },
        { line: "POCKET (poketto) no COIN (koin), soreto", time: 235 },
        { line: "YOU WANNA BE MY FRIEND?", time: 240 },
        { line: "WE ARE, WE ARE ON THE CRUISE!", time: 243 },
        { line: "WE ARE!", time: 246 },
        { line: "WE ARE!", time: 249 },
        { line: "WE ARE!", time: 259 },
      ]
  },
  {
    name: "Somewhere Only We Know",
    singer: "Keane ( cover by Rhianne )",
    src: Song3,
    image:
      "https://i.pinimg.com/564x/ad/69/8f/ad698f9d449f811f8f30ffeeb9ccc347.jpg",
      lyrics:[
        { line: "", time: 41 },
        { line: "Arittake no yume o kakiatsume", note: "Intro", time: 47 },
        { line: "Sagashi-mono o sagashi ni yuku no sa", time: 53 },
        { line: "ONE PIECE", time: 59 },
        {
          line: "Rashinban nante jyutai no moto",
          note: "Verse 1",
          time: 65,
        },
        { line: "Netsu ni ukasare kaji o toru no sa", time: 71 },
        { line: "Hokori kabutteta takara no chizu mo", time: 77 },
        { line: "Tashikameta no nara densetsu jyanai!", time: 82 },
        { line: "Kojin teki na arashi wa dareka no", time: 89 },
        { line: "BIORHYTHM (baiorizumu) nokkatte", time: 94 },
        { line: "omoi sugose ba ii", time: 98 },
        { line: "arittakeno yume o kakiatsume", time: 103 },
        { line: "sagashi mono sagashini yuku no sa", time: 109 },
        { line: "POCKET (poketto) no COIN (koin), soreto", time: 112 },
        { line: "YOU WANNA BE MY FRIEND?", time: 115 },
        { line: "WE ARE, WE ARE ON THE CRUISE! WE ARE!", time: 124 },
        { line: "", time: 156 },
        { line: "zembu mani ukete shinji chattemo",note:"Verse 2", time: 162 },
        { line: "kata o osarete iippo LEAD (lidu) sa", time: 168 },
        { line: "kondo aetanara hanasu tsumorisa", time: 173 },
        { line: "sore kara no koto to kore kara no koto", time: 180 },
        { line: "tsumari itsumo PINCH (pinchi) wa dareka ni", time: 186 },
        { line: "APPEAL (apiiru) dekiru ii CHANCE (chansu)", time: 192 },
        { line: "ji ishiki kajyoo ni!", time: 194 },
        { line: "shimittareta yoru o buttobase!", time: 201 },
        { line: "takara bako ni KYOUMI wa nai kedo", time: 206 },
        { line: "POCKET (poketto) ni roman, soreto", time: 210 },
        { line: "YOU WANNA BE MY FRIEND?", time: 213 },
        { line: "WE ARE, WE ARE ON THE CRUISE! WE ARE!", time: 221 },
        { line: "arittakeno yume o kakiatsume", time: 226 },
        { line: "sagashi mono sagashini yuku no sa", time: 231 },
        { line: "POCKET (poketto) no COIN (koin), soreto", time: 235 },
        { line: "YOU WANNA BE MY FRIEND?", time: 240 },
        { line: "WE ARE, WE ARE ON THE CRUISE!", time: 243 },
        { line: "WE ARE!", time: 246 },
        { line: "WE ARE!", time: 249 },
        { line: "WE ARE!", time: 259 },
      ]
  },
  {
    name: "WE ARE",
    singer: "9 Member",
    src: Song4,
    image:
      "https://i.pinimg.com/564x/ad/69/8f/ad698f9d449f811f8f30ffeeb9ccc347.jpg",
      lyrics:[
        { line: "", time: 41 },
        { line: "Arittake no yume o kakiatsume", note: "Intro", time: 47 },
        { line: "Sagashi-mono o sagashi ni yuku no sa", time: 53 },
        { line: "ONE PIECE", time: 59 },
        {
          line: "Rashinban nante jyutai no moto",
          note: "Verse 1",
          time: 65,
        },
        { line: "Netsu ni ukasare kaji o toru no sa", time: 71 },
        { line: "Hokori kabutteta takara no chizu mo", time: 77 },
        { line: "Tashikameta no nara densetsu jyanai!", time: 82 },
        { line: "Kojin teki na arashi wa dareka no", time: 89 },
        { line: "BIORHYTHM (baiorizumu) nokkatte", time: 94 },
        { line: "omoi sugose ba ii", time: 98 },
        { line: "arittakeno yume o kakiatsume", time: 103 },
        { line: "sagashi mono sagashini yuku no sa", time: 109 },
        { line: "POCKET (poketto) no COIN (koin), soreto", time: 112 },
        { line: "YOU WANNA BE MY FRIEND?", time: 115 },
        { line: "WE ARE, WE ARE ON THE CRUISE! WE ARE!", time: 124 },
        { line: "", time: 156 },
        { line: "zembu mani ukete shinji chattemo",note:"Verse 2", time: 162 },
        { line: "kata o osarete iippo LEAD (lidu) sa", time: 168 },
        { line: "kondo aetanara hanasu tsumorisa", time: 173 },
        { line: "sore kara no koto to kore kara no koto", time: 180 },
        { line: "tsumari itsumo PINCH (pinchi) wa dareka ni", time: 186 },
        { line: "APPEAL (apiiru) dekiru ii CHANCE (chansu)", time: 192 },
        { line: "ji ishiki kajyoo ni!", time: 194 },
        { line: "shimittareta yoru o buttobase!", time: 201 },
        { line: "takara bako ni KYOUMI wa nai kedo", time: 206 },
        { line: "POCKET (poketto) ni roman, soreto", time: 210 },
        { line: "YOU WANNA BE MY FRIEND?", time: 213 },
        { line: "WE ARE, WE ARE ON THE CRUISE! WE ARE!", time: 221 },
        { line: "arittakeno yume o kakiatsume", time: 226 },
        { line: "sagashi mono sagashini yuku no sa", time: 231 },
        { line: "POCKET (poketto) no COIN (koin), soreto", time: 235 },
        { line: "YOU WANNA BE MY FRIEND?", time: 240 },
        { line: "WE ARE, WE ARE ON THE CRUISE!", time: 243 },
        { line: "WE ARE!", time: 246 },
        { line: "WE ARE!", time: 249 },
        { line: "WE ARE!", time: 259 },
      ]
  }
];

export { songs };